name: Build to ECR and deploy to EC2

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image and push to ECR
        uses: docker/build-push-action@v4
        with:
          context: ./nextjs
          push: true
          tags: ${{ secrets.ECR_REGISTRY }}/apwork-nextjs:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          script: |
            mkdir -p /home/ec2-user/apwork
            cd /home/ec2-user/apwork

            if [ ! -d ".git" ]; then
              git init
              git remote add origin https://github.com/genestash/apwork.git
            fi

            git config core.sparseCheckout true
            echo "docker-compose.yml" > .git/info/sparse-checkout
            echo "nginx/" >> .git/info/sparse-checkout
            git pull origin main

            aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
            docker pull ${{ secrets.ECR_REGISTRY }}/apwork-nextjs:latest
            docker tag ${{ secrets.ECR_REGISTRY }}/apwork-nextjs:latest apwork-nextjs:latest

            docker compose down
            docker compose up -d
            docker system prune -f
