name: Deploy to EC2

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./nextjs
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/apwork-nextjs:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.EC2_IP }}
          username: ec2-user
          script: |
            cd /home/ec2-user/apwork
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/apwork-nextjs:latest
            docker tag ${{ secrets.DOCKERHUB_USERNAME }}/apwork-nextjs:latest apwork-nextjs:latest
            docker compose down
            docker compose up -d
            docker system prune -f
