name: Manual Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.EC2_IP }}
          username: ec2-user
          script: |
            if [ ! -d "/home/ec2-user/apwork/.git" ]; then
              git clone https://github.com/genestash/apwork.git /home/ec2-user/apwork
            else
              cd /home/ec2-user/apwork && git pull origin main
            fi
            cd /home/ec2-user/apwork
            docker compose down
            docker compose up -d --build
