name: Deploy to EC2

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./nextjs
          push: true
          tags: 440744247704.dkr.ecr.us-east-2.amazonaws.com/apwork:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.EC2_IP }}
          username: ec2-user
          script: |
            mkdir -p /home/ec2-user/apwork
            cd /home/ec2-user/apwork

            if [ ! -d ".git" ]; then
              git init
              git remote add origin https://github.com/genestash/apwork.git
            fi

            git config core.sparseCheckout true
            echo "docker-compose.yml" > .git/info/sparse-checkout
            echo "nginx/" >> .git/info/sparse-checkout
            git pull origin main

            aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 440744247704.dkr.ecr.us-east-2.amazonaws.com
            docker pull 440744247704.dkr.ecr.us-east-2.amazonaws.com/apwork:latest
            docker tag 440744247704.dkr.ecr.us-east-2.amazonaws.com/apwork:latest apwork-nextjs:latest

            docker compose down
            docker compose up -d
            docker system prune -f
